# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 14:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
