# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 13:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularentry',
            options={'verbose_name_plural': 'Regular Entries'},
        ),
        migrations.AlterModelOptions(
            name='specialentry',
            options={'verbose_name_plural': 'Special Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialentry',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nhour.Activity'),
        ),
    ]
