# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
