# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-year', '-week')},
        ),
    ]
