# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0002_auto_20170503_1351'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE EXTENSION plpythonu;
        CREATE EXTENSION unaccent;

        CREATE FUNCTION weekToDate(year integer, week integer) RETURNS timestamp
        AS $$
        from datetime import datetime
        return datetime.strptime("{}-{} Mon".format(year, week), '%Y-%W %a')
        $$ LANGUAGE plpythonu;

        CREATE VIEW regulars AS
        SELECT weekToDate(entry.year, entry.week) AS date, entry.year as Year, entry.week as Week, entry.hours as Hours, unaccent(system.name) AS System, unaccent(project.name) AS Project, unaccent(task.name) AS Task, unaccent(concat(u.first_name, ' ', u.last_name)) AS Submitter
        FROM nhour_entry entry
            JOIN nhour_regularentry regularentry on regularentry.entry_ptr_id = entry.id
            JOIN auth_user u ON u.id = entry.user_id
            JOIN nhour_system system ON system.id = regularentry.system_id
            JOIN nhour_task task ON task.id = regularentry.task_id
            LEFT JOIN nhour_project project ON regularentry.project_id = project.id;
        """)
    ]
