# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0002_auto_20160216_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
