# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nhour', '0003_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
