# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0006_auto_20160226_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='week',
            field=models.IntegerField(),
        ),
    ]
