# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0007_auto_20160304_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_systems',
            field=models.ManyToManyField(to='nhour.System'),
        ),
    ]
