# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0008_project_related_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
