# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 12:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhour', '0009_entry_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
